# Generated by Django 3.0.7 on 2021-02-21 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_billingprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91 9999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{1,10}$')]),
        ),
    ]
