# Generated by Django 3.0.7 on 2021-02-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20210221_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
