# Generated by Django 3.0.7 on 2020-07-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
