# Generated by Django 3.0.7 on 2021-02-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210228_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
