# Generated by Django 3.0.7 on 2021-03-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210228_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
