# Generated by Django 3.0.7 on 2020-08-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200806_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('returned', 'Returned'), ('refunded', 'Refunded')], default='created', max_length=120),
        ),
    ]
