# Generated by Django 3.0.7 on 2021-03-12 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Just type the name. Extension will be add automatically')]),
        ),
    ]
