# Generated by Django 3.0.7 on 2021-03-12 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210312_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_- ]*$', 'Just type the name. Extension will be add automatically')]),
        ),
    ]
