# Generated by Django 3.0.7 on 2021-03-12 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210312_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfile',
            options={},
        ),
        migrations.AlterField(
            model_name='productfile',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z 0-9_-]*$', 'Just type the name. Extension will be add automatically')]),
        ),
    ]
